config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :users
  resources :events do
  	resources :attendances, except: [:new, :show, :edit] do
  		resources :charges
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user

  after_create :participation_send

	def participation_send
		UserMailer.participation_email(self).deliver_now
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: "User"
  
  

  validates :start_date, 
    presence: {message: "Merci de saisir une date !"}
  validate :is_in_future?

  validates :duration, 
    presence: {message: "Merci de saisir une durée !"}
  validate :divisible_by_five

  validates :title, 
    presence: {message: "Merci de saisir un titre !"},
    length: {minimum: 5, maximum: 140, message: "Le titre doit être entre 5 et 140 caractères"}
  validates :description, 
    presence: {message: "Merci de saisir un contenu !"},
    length: {minimum: 20, maximum: 1000, message: "La description doit être entre 20 et 1000 caractères"}
  validates :price,
    presence: {message: "Merci de saisir un prix !"},
    numericality: { in: 1..1000 }
  validates :location, 
    presence: {message: "Merci de saisir une ville !"}


  def divisible_by_five
    if duration % 5 != 0
			errors.add(:duration, "La durée doit être un multiple de 5")
		end
  end

  def is_in_future?
		if start_date.to_date < DateTime.now.to_date
			errors.add(:start_date, "Date dépassée")
		end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :attendances
  has_many :events
  has_many :events, through: :attendances
  


  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #Authorise le rajout des autres champs de l'enregistrement

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :is_alive, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :is_alive, :email, :password, :password_confirmation)}
  end

end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
    
    @event=Event.find(params[:event_id])
    @attendees=@event.users
    
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @event = Event.new
  end

  def create
   
    @event = Event.new(
      title:params[:title],
      description:params[:description],
      location:params[:location],
      price:params[:price],
      duration:params[:duration],
      start_date:params[:start_date],
      admin: current_user
      )
    #@event.admin = current_user

      if @event.save
        redirect_to event_path(@event.id)
      else
         render :new
      end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def edit
    @event= Event.find(params[:id])
  end

  def update
    @event= Event.find(params[:id])
      if @event=Event.update(
        title: params[:title],
        price:params[:price],
        description:params[:description],
        admin_id:current_user.id,
        location: params[:location],
        start_date:params[:start_date],
        duration:params[:duration]
        )
      redirect_to event_path(@event.id)
		else
		  render edit
		end 
  end

  def destroy
    @event= Event.find(params[:id])
		@event.destroy
		redirect_to events_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :authenticate_user!, only: [:show]
  before_action :right_user

  def show

    if params[:id].to_i == current_user.id.to_i
      @current_user = current_user
      @my_admin_events = Event.where(admin_id: params[:id])
    else
      redirect_to root_url
    end
 
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def test_current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def right_user
  	unless current_user == User.find(params[:id])
	    redirect_to new_user_session_path
	  end
  end

end

app/views/attendances/index.html.erb
<div>
  <p>Voici la liste des personnes présentes à votre événement </p>
  <% @attendees.each do |user| %><br>
    <p class="card-text"><%= user.first_name  %> <%= user.last_name  %> </p>
  <% end %>
</div><br/>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag event_attendance_charges_path(@event.id,current_user.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Cet évènement coute : </span>
      <span><%= @event.price %> € </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description=<%= @event.title %>
          data-amount=<%= @event.price*100 %>
          data-locale="auto"></script>
<% end %>

app/views/events/index.html.erb
<h1 class="font-weight-light">Trouvez votre evenement !</h1>
<p class="lead"></p>

<% @events.each do |one_event| %><br>

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" url="<%event_path(one_event.id)%>" src="https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=100&q=60/" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= one_event.title  %></h5>
      <p class="card-text"><%= one_event.description  %></p>
      <a class="btn btn-primary" <%= link_to "En savoir plus", event_path(one_event.id)%></a>
    </div>
  </div>
  <br />

 <% end %>

app/views/events/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'Le titre' %>
    </div>
    <div class="col-3">
    <%= text_field_tag 'title', value = nil, options = {style:"width:100%"} %>
    </div>
  </div>     
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'La description' %>
    </div>
    <div class="col-3">
    <%= text_area_tag 'description', value = Faker::ChuckNorris.fact*2, options = {style:"width:100%"} %>
    </div>
  </div>
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'La durée' %>
    </div>
    <div class="col-3">
    <%= text_field_tag 'duration', value = (5*rand(1..20)), options = {style:"width:100%"} %>
    </div>
  </div>     
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'Le prix' %>
    </div>
    <div class="col-3">
    <%= text_field_tag 'price', value = rand(1..1000), options = {style:"width:100%"} %>
    </div>
  </div>     
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'Le lieu' %>
    </div>
    <div class="col-3">
    <%= text_field_tag 'location', value = Faker::Address.city, options = {style:"width:100%"} %>
    </div>
  </div>     
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
    <%= label_tag 'La date' %>
    </div>
    <div class="col-3">
    <%= date_field_tag 'start_date', value = Faker::Date.forward(days: 40), options = {style:"width:100%"} %>
    </div>
  </div>     
  <br />

  <div class="row justify-content-center align-self-center mx-5">
    <div class="col-3">
      <%= submit_tag "Valider", class: 'btn btn-primary'  %>
    </div>
  </div>
  <br />

<% end %>

app/views/events/show.html.erb
<h1 class="font-weight-light">Détail de l'évenement</h1>
<br/>
<div>
  <h2 class="font-weight-light">Début : </h2>
  <%=@event.start_date%> <br/>
</div><br/>

<% if user_signed_in? && @event.admin_id == current_user.id%>
  <a class="btn btn-danger" <%= link_to "Voir mon event", event_attendances_path(@event.id)%>
<% elsif user_signed_in? && @event.users.ids.include?(current_user.id)%>
  <div class="text-muted font-weight-bold">Vous êtes inscrit à cet event.</div>
<%elsif user_signed_in?%>
  <a class="btn btn-danger" <%= link_to "S'inscrire", new_event_attendance_charge_path(@event.id,current_user.id)%>
<%end%>

<div>
<h2 class="font-weight-light">Durée : </h2>
<%=@event.duration%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Titre : </h2>
<%=@event.title%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Description : </h2>
<%=@event.description%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Prix : </h2>
<%=@event.price%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Ville : </h2>
<%=@event.location%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Admin : </h2>
<%=@event.admin_id%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Créé le : </h2>
<%=@event.created_at%><br/>
</div><br/>

<div>
<h2 class="font-weight-light">Mise à jour le : </h2>
<%=@event.updated_at%><br/>
</div><br/>



<a class="btn btn-primary" <%= link_to "Gérer", event_attendances_path(@event.id)%></a>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  
  </head>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">EventBrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" href="<%= new_event_path %>">Créer un événement</a>
    </li>
    <%if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" href="" aria-expanded="false"><%= current_user.first_name %></a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon profil</a>
          <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>
        </div>
      </li>
    <%else%>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" href="" aria-expanded="false">S'inscrire / Se connecter</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
          <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
        </div>
      </li>
    <%end%>

  </ul>
      </div>
    </div>
  </nav>
 
 <body>

  <!-- Page Content -->
  <div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">
        
         <%= yield %>

      </div>
    </div>
  </div>
  
  </body>

  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small> ©Julien @ THP2019</small>
    </div>
  </section>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  
  </head>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">EventBrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" href="<%= new_event_path %>">Créer un événement</a>
    </li>
    <%if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" href="" aria-expanded="false"><%= current_user.first_name %></a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon profil</a>
          <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>
        </div>
      </li>
    <%else%>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" href="" aria-expanded="false">S'inscrire / Se connecter</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
          <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
        </div>
      </li>
    <%end%>

  </ul>
      </div>
    </div>
  </nav>
 
 <body>

  <!-- Page Content -->
  <div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">
        
         <%= yield %>

      </div>
    </div>
  </div>
  
  </body>

  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small> ©Julien @ THP2019</small>
    </div>
  </section>

</html>




app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<h1 class="font-weight-light">Mon profil</h1>


  <h2 class="font-weight-light">Mes infos </h2>

    <h3 class="font-weight-light">Mon email : </h3>
      <%=@current_user.email%> <br/><br/>

    <h3 class="font-weight-light">Description : </h3>
      <%=@current_user.description%> <br/><br/>

    <h3 class="font-weight-light">Prénom : </h3>
      <%=@current_user.first_name%> <br/><br/>

    <h3 class="font-weight-light">Nom : </h3>
      <%=@current_user.last_name%> <br/><br/>

    <h3 class="font-weight-light">Membre depuis : </h3>
      <%=@current_user.created_at%> <br/><br/>

  <h2 class="font-weight-light">Mes événements </h2><br/>


<% @my_admin_events.each do |one_event| %><br>

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" url="<%event_path(one_event.id)%>" src="https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=100&q=60/" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= one_event.title  %></h5>
      <p class="card-text"><%= one_event.description  %></p>
      <a class="btn btn-primary" <%= link_to "En savoir plus", event_path(one_event.id)%></a>
    </div>
  </div>
  <br />

 <% end %>




